//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEsferoCliente.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SWServicioEsfero")]
    public interface SWServicioEsfero {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEsferoCliente.ServiceReference1.insertarResponse insertar(AppEsferoCliente.ServiceReference1.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.insertarResponse> insertarAsync(AppEsferoCliente.ServiceReference1.insertarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEsferoCliente.ServiceReference1.eliminarResponse eliminar(AppEsferoCliente.ServiceReference1.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.eliminarResponse> eliminarAsync(AppEsferoCliente.ServiceReference1.eliminarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEsferoCliente.ServiceReference1.actualizarResponse actualizar(AppEsferoCliente.ServiceReference1.actualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.actualizarResponse> actualizarAsync(AppEsferoCliente.ServiceReference1.actualizarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEsferoCliente.ServiceReference1.listarResponse listar(AppEsferoCliente.ServiceReference1.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.listarResponse> listarAsync(AppEsferoCliente.ServiceReference1.listarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEsferoCliente.ServiceReference1.consultarResponse consultar(AppEsferoCliente.ServiceReference1.consultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.consultarResponse> consultarAsync(AppEsferoCliente.ServiceReference1.consultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void notificarObservadores();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task notificarObservadoresAsync();
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void agregarObservador(AppEsferoCliente.ServiceReference1.agregarObservador request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task agregarObservadorAsync(AppEsferoCliente.ServiceReference1.agregarObservador request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class esfero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string colorTintaField;
        
        private string marcaField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string colorTinta {
            get {
                return this.colorTintaField;
            }
            set {
                this.colorTintaField = value;
                this.RaisePropertyChanged("colorTinta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class aActualizableEsfero : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEsferoCliente.ServiceReference1.esfero arg0;
        
        public insertarRequest() {
        }
        
        public insertarRequest(AppEsferoCliente.ServiceReference1.esfero arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class actualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEsferoCliente.ServiceReference1.esfero arg0;
        
        public actualizarRequest() {
        }
        
        public actualizarRequest(AppEsferoCliente.ServiceReference1.esfero arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class actualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarResponse() {
        }
        
        public actualizarResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listarRequest {
        
        public listarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEsferoCliente.ServiceReference1.esfero[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(AppEsferoCliente.ServiceReference1.esfero[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class consultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public consultarRequest() {
        }
        
        public consultarRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class consultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEsferoCliente.ServiceReference1.esfero @return;
        
        public consultarResponse() {
        }
        
        public consultarResponse(AppEsferoCliente.ServiceReference1.esfero @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarObservador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class agregarObservador {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEsferoCliente.ServiceReference1.aActualizableEsfero arg0;
        
        public agregarObservador() {
        }
        
        public agregarObservador(AppEsferoCliente.ServiceReference1.aActualizableEsfero arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWServicioEsferoChannel : AppEsferoCliente.ServiceReference1.SWServicioEsfero, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWServicioEsferoClient : System.ServiceModel.ClientBase<AppEsferoCliente.ServiceReference1.SWServicioEsfero>, AppEsferoCliente.ServiceReference1.SWServicioEsfero {
        
        public SWServicioEsferoClient() {
        }
        
        public SWServicioEsferoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWServicioEsferoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWServicioEsferoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWServicioEsferoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEsferoCliente.ServiceReference1.insertarResponse AppEsferoCliente.ServiceReference1.SWServicioEsfero.insertar(AppEsferoCliente.ServiceReference1.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public bool insertar(AppEsferoCliente.ServiceReference1.esfero arg0) {
            AppEsferoCliente.ServiceReference1.insertarRequest inValue = new AppEsferoCliente.ServiceReference1.insertarRequest();
            inValue.arg0 = arg0;
            AppEsferoCliente.ServiceReference1.insertarResponse retVal = ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.insertarResponse> AppEsferoCliente.ServiceReference1.SWServicioEsfero.insertarAsync(AppEsferoCliente.ServiceReference1.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.insertarResponse> insertarAsync(AppEsferoCliente.ServiceReference1.esfero arg0) {
            AppEsferoCliente.ServiceReference1.insertarRequest inValue = new AppEsferoCliente.ServiceReference1.insertarRequest();
            inValue.arg0 = arg0;
            return ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEsferoCliente.ServiceReference1.eliminarResponse AppEsferoCliente.ServiceReference1.SWServicioEsfero.eliminar(AppEsferoCliente.ServiceReference1.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public bool eliminar(int arg0) {
            AppEsferoCliente.ServiceReference1.eliminarRequest inValue = new AppEsferoCliente.ServiceReference1.eliminarRequest();
            inValue.arg0 = arg0;
            AppEsferoCliente.ServiceReference1.eliminarResponse retVal = ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.eliminarResponse> AppEsferoCliente.ServiceReference1.SWServicioEsfero.eliminarAsync(AppEsferoCliente.ServiceReference1.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.eliminarResponse> eliminarAsync(int arg0) {
            AppEsferoCliente.ServiceReference1.eliminarRequest inValue = new AppEsferoCliente.ServiceReference1.eliminarRequest();
            inValue.arg0 = arg0;
            return ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEsferoCliente.ServiceReference1.actualizarResponse AppEsferoCliente.ServiceReference1.SWServicioEsfero.actualizar(AppEsferoCliente.ServiceReference1.actualizarRequest request) {
            return base.Channel.actualizar(request);
        }
        
        public bool actualizar(AppEsferoCliente.ServiceReference1.esfero arg0) {
            AppEsferoCliente.ServiceReference1.actualizarRequest inValue = new AppEsferoCliente.ServiceReference1.actualizarRequest();
            inValue.arg0 = arg0;
            AppEsferoCliente.ServiceReference1.actualizarResponse retVal = ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).actualizar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.actualizarResponse> AppEsferoCliente.ServiceReference1.SWServicioEsfero.actualizarAsync(AppEsferoCliente.ServiceReference1.actualizarRequest request) {
            return base.Channel.actualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.actualizarResponse> actualizarAsync(AppEsferoCliente.ServiceReference1.esfero arg0) {
            AppEsferoCliente.ServiceReference1.actualizarRequest inValue = new AppEsferoCliente.ServiceReference1.actualizarRequest();
            inValue.arg0 = arg0;
            return ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).actualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEsferoCliente.ServiceReference1.listarResponse AppEsferoCliente.ServiceReference1.SWServicioEsfero.listar(AppEsferoCliente.ServiceReference1.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public AppEsferoCliente.ServiceReference1.esfero[] listar() {
            AppEsferoCliente.ServiceReference1.listarRequest inValue = new AppEsferoCliente.ServiceReference1.listarRequest();
            AppEsferoCliente.ServiceReference1.listarResponse retVal = ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.listarResponse> AppEsferoCliente.ServiceReference1.SWServicioEsfero.listarAsync(AppEsferoCliente.ServiceReference1.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.listarResponse> listarAsync() {
            AppEsferoCliente.ServiceReference1.listarRequest inValue = new AppEsferoCliente.ServiceReference1.listarRequest();
            return ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).listarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEsferoCliente.ServiceReference1.consultarResponse AppEsferoCliente.ServiceReference1.SWServicioEsfero.consultar(AppEsferoCliente.ServiceReference1.consultarRequest request) {
            return base.Channel.consultar(request);
        }
        
        public AppEsferoCliente.ServiceReference1.esfero consultar(int arg0) {
            AppEsferoCliente.ServiceReference1.consultarRequest inValue = new AppEsferoCliente.ServiceReference1.consultarRequest();
            inValue.arg0 = arg0;
            AppEsferoCliente.ServiceReference1.consultarResponse retVal = ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).consultar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.consultarResponse> AppEsferoCliente.ServiceReference1.SWServicioEsfero.consultarAsync(AppEsferoCliente.ServiceReference1.consultarRequest request) {
            return base.Channel.consultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEsferoCliente.ServiceReference1.consultarResponse> consultarAsync(int arg0) {
            AppEsferoCliente.ServiceReference1.consultarRequest inValue = new AppEsferoCliente.ServiceReference1.consultarRequest();
            inValue.arg0 = arg0;
            return ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).consultarAsync(inValue);
        }
        
        public void notificarObservadores() {
            base.Channel.notificarObservadores();
        }
        
        public System.Threading.Tasks.Task notificarObservadoresAsync() {
            return base.Channel.notificarObservadoresAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AppEsferoCliente.ServiceReference1.SWServicioEsfero.agregarObservador(AppEsferoCliente.ServiceReference1.agregarObservador request) {
            base.Channel.agregarObservador(request);
        }
        
        public void agregarObservador(AppEsferoCliente.ServiceReference1.aActualizableEsfero arg0) {
            AppEsferoCliente.ServiceReference1.agregarObservador inValue = new AppEsferoCliente.ServiceReference1.agregarObservador();
            inValue.arg0 = arg0;
            ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).agregarObservador(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task AppEsferoCliente.ServiceReference1.SWServicioEsfero.agregarObservadorAsync(AppEsferoCliente.ServiceReference1.agregarObservador request) {
            return base.Channel.agregarObservadorAsync(request);
        }
        
        public System.Threading.Tasks.Task agregarObservadorAsync(AppEsferoCliente.ServiceReference1.aActualizableEsfero arg0) {
            AppEsferoCliente.ServiceReference1.agregarObservador inValue = new AppEsferoCliente.ServiceReference1.agregarObservador();
            inValue.arg0 = arg0;
            return ((AppEsferoCliente.ServiceReference1.SWServicioEsfero)(this)).agregarObservadorAsync(inValue);
        }
    }
}
